version: 2.0.0-rc.7

build:
  command: cargo build --workspace --target wasm32-wasip2 --release
  component_path: target/wasm32-wasip2/release/http_api.wasm

dev:
  wasi_keyvalue_cloudflare: x
  wasi_blobstore_cloudflare: x
  components:
    - name: task-leet
      file: target/wasm32-wasip2/release/task_leet.wasm
  #   - name: cf-r2
  #     file: target/wasm32-wasip2/release/cf_r2.wasm
  #     config:
  #       cf_account_id: 4e4a9cbc00e5e3a6c07597fb44cf7be4
  #       cf_api_token: cfut_Ntwhi2Yt7ZfvFEGMROM2ieE6ioPbALZ84ZLhoIrh2329e0d4
  #       cf_bucket_name: wasmcloud-v2
  #       cf_access_key: a766ff51144201160836e49577d199f1
  #       cf_secret_key: df4b71b112492097af3e341160911388f5b1391e7821b7c6c02060ee69b48b72
  #   - name: cf-kv
  #     file: target/wasm32-wasip2/release/cf_kv.wasm
  #     config:
  #       cf_account_id: 4e4a9cbc00e5e3a6c07597fb44cf7be4
  #       cf_api_token: 8pTPivMklAfqBdQ1zMx0loXQL0mEeDOcUCC09dw4
  #       cf_namespace_id: 084a73f4e44d40679f8f3eb5bc4bbf61
  host_interfaces:
    - namespace: wasi
      package: keyvalue
      interfaces:
        - store
      config:
        account_id: 4e4a9cbc00e5e3a6c07597fb44cf7be4
        api_token: 8pTPivMklAfqBdQ1zMx0loXQL0mEeDOcUCC09dw4
        namespace_id: 084a73f4e44d40679f8f3eb5bc4bbf61
    - namespace: wasi
      package: blobstore
      interfaces:
        - types
        - container
        - blobstore
      config:
        # # Memory (default, no config needed)
        # backend: memory

        # S3 (Cloudflare R2)
        backend: s3
        root: "/"
        bucket: wasmcloud-v2
        region: auto
        endpoint: https://4e4a9cbc00e5e3a6c07597fb44cf7be4.r2.cloudflarestorage.com
        access_key_id: a766ff51144201160836e49577d199f1
        secret_access_key: df4b71b112492097af3e341160911388f5b1391e7821b7c6c02060ee69b48b72

        # # WebDAV
        # backend: "webdav"
        # endpoint: "https://dav.example.com/"
        # username: "user"
        # password: "pass"

        # # FTP
        # backend: "ftp"
        # endpoint: "ftp://ftp.example.com"
        # username: "user"
        # password: "pass"

        # # S3
        # backend: "s3"
        # bucket: "my-bucket"
        # region: "us-east-1"
        # endpoint: "https://s3.amazonaws.com"
        # access_key_id: "xxx"
        # secret_access_key: "xxx"

        # # Filesystem
        # backend: "fs"
        # root: "/tmp/blobstore"

    - namespace: custom
      package: cf-d1
      interfaces:
        - query
      config:
        account_id: 4e4a9cbc00e5e3a6c07597fb44cf7be4
        api_token: cfut_MYnNBIzZZBjgrcTMt0ZXrbNBocs2BU2bRvubOF8Qa345f31d
        database_id: 1995ea7e-d2b1-42ab-9556-82dbd8a5b6e9
    - namespace: custom
      package: llm-gateway
      interfaces:
        - chat
        # - chat-streaming
      config:
        provider: openai-compat
        base_url: https://openrouter.ai/api/v1/
        # base_url: https://openrouter.ai/api/v1/chat/completions
        model_name: z-ai/glm-4.5-air:free
        api_key: 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
    - namespace: custom
      package: dingtalk-stream
      interfaces:
        - sender
      config:
        client-id: dingyoneajfa6v5iimh5
        client-secret: z22GV9SayKtdhUVEN6i1qkZr3983ciMvzdvlM8MWKvHHP2nscbDOawCaHCSx7Ob0
    - namespace: custom
      package: feishu
      interfaces:
        - sender
      config:
        app-id: cli_a946044d55f99bde
        app-secret: oFk1iE8PibychCsyYhX9qcLQqS70lTqd
    - namespace: custom
      package: mail
      interfaces:
        - sender
      config:
        smtp-host: x
        smtp-port: "80"
        username: y
        password: z
        default-from: a

new:
  command: cargo fetch
